[package]
name = "wol_webhook"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
simplelog = "0.12.2"